### ISSUE TITLE
Missing Swap Protocol Logs on Kibana

### ISSUE THREAD

**Issue by EbubeUd** [status-im/infra-nim-waku#15]
Currently, logs from the `Swap` protocol are not displayed on Kibana. 

Solution:
The solution to this is to enable `Swap` in the docker-compose.yml file, as stated here:
[#573](https://github.com/status-im/nim-waku/issues/573)

**Comment by oskarth** [comment]
You should be able to do just do a PR with that command line flag enabled, just as was done for `lightpush` here https://github.com/status-im/infra-nim-waku/pull/12

cc @jm-clius @jakubgs

**Comment by oskarth** [comment]
@jakubgs it isn't clear to me how we'd distinguish test from prod in that template, might be nice to programmatically specify config used in test vs prod? Especially as we'll want to have some experimental things enabled in test fleet but not in produ fleet

**Comment by jakubgs** [comment]
Prod and test are differentiated based on group names. You can just prametrize the flag and then set different values here:

* https://github.com/status-im/infra-nim-waku/blob/master/ansible/group_vars/wakuv2-test.yml
* https://github.com/status-im/infra-nim-waku/blob/master/ansible/group_vars/wakuv2-prod.yml

Though I guess currently they look identical. Another way is to have global config but use something like:
```
nim_waku_swap_protocol_enabled: '{{ stage == "prod" }}'
```
But since we have separate group files might as well use that.

**Comment by jakubgs** [comment]
Deployed: https://github.com/status-im/infra-nim-waku/pull/16#issuecomment-851319503
