### ISSUE TITLE
Renaming of Nim-Waku V2 fleets for consistency

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-nim-waku#27]
I have set up a new  [infra-go-waku](https://github.com/status-im/infra-go-waku) fleet as requested by @richard-ramos, configured in the same manner as `infra-nim-waku`.

The small issue with that is that the current naming of hosts and fleets does not include the language used, which is confusing.

Currently the fleet names are `wakuv2.{test.prod}`, and my idea is to rename those to just `nim-waku.{test.prod}` in the same schema as `go-waku.{test,prod}`. I want to drop the `v2` since Waku V1 is in maintenance mode essentially and we mostly use or talk about V2, so it seems not useful and would improve brevity of naming. Of course we would have a transitory period where both old and new naming schemes are available under https://fleets.status.im/.

I'd like some feedback from @richard-ramos, @oskarth and @jm-clius.

**Comment by oskarth** [comment]
1) In principle having name of node software in fleet makes sense to me
2) Can we do this in backwards compatible way? I.e. with a redirect or so. Waku v2 is out in the wild, and projects like WalletConnect + god knows what DappConnect projects are relying on being able to find nodes through this URL
3) I wouldn't remove v2, at least not now
- Why do we want this? Brevity seems like a weak argument because it is less precise
- v1 is still live and will be for a while, if we definitely want to do this seems wiser to wait until mobile is live + N months, also see bridging and point 2 above
- What about when v3 comes? :P

Also cc @D4nte

**Comment by jakubgs** [comment]
>Why do we want this? Brevity seems like a weak argument because it is less precise

Consistency in naming. It's in the issue title.

>v1 is still live and will be for a while, if we definitely want to do this seems wiser to wait until mobile is live + N months, also see bridging and point 2 above

V1 will never be hosted by anything other than `status-go`, the only purpose of `nim-waku` V1 is to bridge with V2. As far as I can tell the only relevant version of `nim-waku` is v2. But whatever, we can keep `v2` as long as naming is consistent:
```
go-waku-v2.test
nim-waku-v2.test
nim-waku-v2.prod
```

>What about when v3 comes? :P

You have to be joking.

**Comment by jakubgs** [comment]
>Waku v2 is out in the wild, and projects like WalletConnect + god knows what DappConnect projects are relying on being able to find nodes through this URL.

And that should have never happened. Maybe it's a good idea to wean them off of it? How's the work on DNS discovery?

https://fleets.status.im/ was ONLY intended for use with CI builds of Status app, but naturally people kept sharing it and now they use it as source of addresses of our nodes. I don't think they should rely on it, and the change in naming would actually be a good wakeup call to use an actual discovery method like DNS. But that has to be in place and usable first.

**Comment by oskarth** [comment]
Let's wait to hear from @jm-clius and @D4nte re what assumptions are made on that URL, if any. I could be wrong.
