### ISSUE TITLE
launch a node in Singapore instead of HK (Asia)

### ISSUE THREAD

**Issue by danisharora099** [status-im/infra-nim-waku#83]
in reference to https://github.com/waku-org/js-waku/issues/1465#issuecomment-1679957054, it seems a better option to launch a node in Singapore instead of Hong Kong for Asia

**Comment by jakubgs** [comment]
I don't think this is easily doable for 3 reasons:

* We run Consul clusters in each Data Center we, as well as metrics and logs hosts.
  - I don't want to deploy a set of those only to support one or two nodes for this fleet.
* We use a Terraform module called [`infra-tf-multi-provider`](https://github.com/status-im/infra-tf-multi-provider) that assumes a DC in Alibaba cloud.
  - The zone is [hardcoded](https://github.com/status-im/infra-tf-multi-provider/blob/58397ff4bfa7aeebba9948ad8b08c1da228f3387/module_ac.tf#L53) and changing that would not be trivial.
* Migrating to Singapore would not really be doable for a lot of fleets because we could not preserve IPs.
  - Floating IPs are usually re-usable within a given DC, but not outside of it.

I don't think this change is worth the amount of effort it would require, unless you think it's very high priority.

And honestly, Waku protocol development would benefit from some bad latency =], that's what you should be building it for.

**Comment by fryorcraken** [comment]
Fair comment. Happy to close.

**Comment by jakubgs** [comment]
Now, if you do think this is actually important, we could do a Singapore node IN ADDITION to the Hong Kong one more easily.
Replacing Hong Kong one would be a massive pain, but if you just want one more host, for a total of 4 that would be feasible.

My question though would be, would that be specific to this fleet only? And if so, would it be for all stages or just one?
